name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue App
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'DnD4e'
        reponame: 'dnd4e'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
